# Generated by Django 5.2.9 on 2025-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRestrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observação')),
                ('arquivo', models.FileField(upload_to='intranet_docs/')),
                ('categoria', models.CharField(choices=[('ATA', 'Ata de Reunião'), ('CIRCULAR', 'Circular / Comunicado'), ('FINANCEIRO', 'Relatório Financeiro'), ('ADMIN', 'Documento Administrativo'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento Restrito',
                'verbose_name_plural': 'Documentos Restritos (Intranet)',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
