# Generated by Django 5.2.9 on 2026-08-07 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRestrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observação')),
                ('arquivo', models.FileField(blank=True, max_length=500, null=True, upload_to='intranet_docs/')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link Externo (Google Drive, etc)')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='intranet.categoriadocumento', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Documento Restrito',
                'verbose_name_plural': 'Documentos Restritos (Intranet)',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
