# Generated by Django 5.2.9 on 2025-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentorestrito',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Externo (Google Drive, etc)'),
        ),
        migrations.AlterField(
            model_name='documentorestrito',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='intranet_docs/'),
        ),
    ]
