# Generated by Django 5.2.9 on 2026-08-07 19:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorestrito',
            name='arquivo',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='intranet_docs/'),
        ),
    ]
