# Generated by Django 5.2.9 on 2025-12-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_documentorestrito_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documentos',
            },
        ),
        migrations.AlterField(
            model_name='documentorestrito',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='intranet.categoriadocumento', verbose_name='Categoria'),
        ),
    ]
