# Generated by Django 5.2.9 on 2026-08-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_categoriadocumento_alter_documentorestrito_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadocumento',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='documentorestrito',
            name='titulo',
            field=models.CharField(max_length=500, verbose_name='Título do Documento'),
        ),
    ]
