# Generated by Django 5.2.9 on 2026-06-02 02:14

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, verbose_name='Dia da Semana')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Atividade')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição Curta')),
                ('publico_alvo', models.CharField(default='Público Geral', max_length=100)),
            ],
            options={
                'verbose_name': 'Atividade Semanal',
                'verbose_name_plural': 'Atividades Semanais (Grade Fixa)',
                'ordering': ['dia', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo')),
            ],
            options={
                'verbose_name': 'Cargo Presidência e Departamentos',
                'verbose_name_plural': 'Cargos Presidência e Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_banner', models.CharField(default='Federação Espírita do Piauí', max_length=200)),
                ('subtitulo_banner', models.CharField(default='Unindo corações, esclarecendo mentes e consolando almas.', max_length=300)),
                ('imagem_banner', models.ImageField(blank=True, help_text='Imagem de fundo do topo (Opcional)', null=True, upload_to='banners/')),
                ('popup_ativo', models.BooleanField(default=False, verbose_name='Ativar Pop-up?')),
                ('popup_titulo', models.CharField(blank=True, max_length=100, verbose_name='Título do Pop-up')),
                ('popup_imagem', models.ImageField(blank=True, null=True, upload_to='popup/', verbose_name='Imagem do Pop-up')),
                ('popup_link', models.URLField(blank=True, verbose_name='Link de Destino (Notícia/Curso)')),
                ('popup_botao_texto', models.CharField(default='Saiba Mais', max_length=50, verbose_name='Texto do Botão')),
                ('popup_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início da Exibição')),
                ('popup_fim', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fim da Exibição')),
            ],
            options={
                'verbose_name': 'Configuração da Home (Banner/Pop-up)',
                'verbose_name_plural': 'Configuração da Home (Banner/Pop-up)',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoYouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_mode', models.CharField(choices=[('auto', 'Automático (último do canal)'), ('fixed', 'Fixo (ID informado)'), ('off', 'Desligado')], default='auto', max_length=10, verbose_name='Modo do YouTube')),
                ('youtube_channel_id', models.CharField(blank=True, help_text='Ex: UCxxxx... (ID do canal)', max_length=80, null=True, verbose_name='Channel ID')),
                ('youtube_video_id', models.CharField(blank=True, help_text='Somente o ID do vídeo (ex: ABC1234)', max_length=50, null=True, verbose_name='Video ID (modo fixo)')),
            ],
            options={
                'verbose_name': 'Configuração do YouTube',
                'verbose_name_plural': 'Configuração do YouTube',
            },
        ),
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Evento')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug (URL)')),
                ('data_inicio', models.DateTimeField(verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('local', models.CharField(default='Auditório da FEPI', max_length=200)),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Detalhes do Evento')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Banner/Cartaz')),
                ('link_inscricao', models.URLField(blank=True, null=True, verbose_name='Link de Inscrição')),
                ('valor', models.CharField(blank=True, help_text='Ex: Gratuito ou R$ 20,00', max_length=50, verbose_name='Valor (se houver)')),
                ('destaque_home', models.BooleanField(default=False, verbose_name='Destacar na Home?')),
            ],
            options={
                'verbose_name': 'Evento / Curso',
                'verbose_name_plural': 'Agenda de Eventos e Cursos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InformacaoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(default='R. Olavo Bilac, 1394 - Centro (Sul)', max_length=300)),
                ('cidade', models.CharField(default='Teresina - PI', max_length=100)),
                ('cep', models.CharField(default='64001-280', max_length=20)),
                ('telefone', models.CharField(default='(86) 3221-3021', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario_livraria', models.CharField(default='Segunda à Sábado', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuração de Contato',
                'verbose_name_plural': 'Configuração de Contato',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Notícia')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Resumo / Subtítulo')),
                ('conteudo', ckeditor.fields.RichTextField(verbose_name='Conteúdo Completo')),
                ('autor', models.CharField(default='Assessoria FEPI', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug (URL Amigável)')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem de Capa')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='PaginaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nossa História', max_length=200)),
                ('conteudo', ckeditor.fields.RichTextField(verbose_name='Texto da História')),
                ('frase_destaque', models.CharField(blank=True, max_length=300, verbose_name='Frase de Destaque (Missão)')),
                ('ano_inicio', models.IntegerField(default=2024, verbose_name='Ano Início da Gestão')),
                ('ano_fim', models.IntegerField(default=2027, verbose_name='Ano Fim da Gestão')),
            ],
            options={
                'verbose_name': 'Página Institucional (Texto)',
                'verbose_name_plural': 'Página Institucional (Texto)',
            },
        ),
        migrations.CreateModel(
            name='PalestraPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Horário')),
                ('tema', models.CharField(max_length=200, verbose_name='Tema da Palestra')),
                ('orador', models.CharField(max_length=150, verbose_name='Orador / Expositor')),
                ('casa_espirita', models.CharField(blank=True, help_text='Deixar em branco se for da casa', max_length=150, verbose_name='Casa Espírita (Origem)')),
                ('imagem_divulgacao', models.ImageField(blank=True, null=True, upload_to='palestras/', verbose_name='Cartaz de Divulgação')),
                ('link_transmissao', models.URLField(blank=True, null=True, verbose_name='Link YouTube (se houver)')),
            ],
            options={
                'verbose_name': 'Palestra Pública',
                'verbose_name_plural': 'Agenda de Palestras',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PostInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='instagram/', verbose_name='Imagem do Post')),
                ('link', models.URLField(verbose_name='Link do Post (Instagram)')),
                ('legenda', models.CharField(blank=True, help_text='Texto curto para acessibilidade', max_length=100)),
                ('data_post', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post do Instagram',
                'verbose_name_plural': 'Posts do Instagram (Vitrine)',
                'ordering': ['-data_post'],
            },
        ),
        migrations.CreateModel(
            name='TipoDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Diretoria/Departamento')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição Breve')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Tipo/Departamento',
                'verbose_name_plural': 'Tipos e Departamentos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('centro_espirita', models.CharField(max_length=200, verbose_name='Centro Espírita ou Entidade')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autores/')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Associado (Usuário)')),
            ],
            options={
                'verbose_name': 'Autor/Colaborador',
                'verbose_name_plural': 'Autores/Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.TextField(help_text='Uma breve introdução para atrair o leitor na página inicial.', verbose_name='Resumo')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('conteudo', ckeditor.fields.RichTextField(verbose_name='Conteúdo')),
                ('nome_autor', models.CharField(blank=True, max_length=200, verbose_name='Nome do Autor (Se não for associado)')),
                ('instituicao_autor', models.CharField(blank=True, max_length=200, verbose_name='Instituição')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='colunas/', verbose_name='Imagem de Capa')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Aguardando Revisão'), ('PUBLICADO', 'Publicado')], default='PENDENTE', max_length=15)),
                ('autor_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Associado (Opcional)')),
            ],
            options={
                'verbose_name': 'Coluna/Artigo',
                'verbose_name_plural': 'Colunas e Artigos',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='MembroDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ordem', models.IntegerField(default=0, help_text='Para ordenar dentro do Tipo/Departamento')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo', verbose_name='Cargo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipodiretoria', verbose_name='Tipo/Departamento')),
            ],
            options={
                'verbose_name': 'Membro/Responsável',
                'verbose_name_plural': 'Membros e Responsáveis',
                'ordering': ['tipo__ordem', 'ordem', 'nome'],
            },
        ),
    ]
