# Generated by Django 5.2.9 on 2025-12-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(default='R. Olavo Bilac, 1394 - Centro (Sul)', max_length=300)),
                ('cidade', models.CharField(default='Teresina - PI', max_length=100)),
                ('cep', models.CharField(default='64001-280', max_length=20)),
                ('telefone', models.CharField(default='(86) 3221-3021', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario_livraria', models.CharField(default='Segunda à Sábado', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuração de Contato',
                'verbose_name_plural': 'Configuração de Contato',
            },
        ),
    ]
