# Generated by Django 5.2.9 on 2025-12-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('EXECUTIVA', 'Diretoria Executiva'), ('FISCAL', 'Conselho Fiscal')], default='EXECUTIVA', max_length=20)),
                ('ordem', models.IntegerField(default=0, help_text='Use números para ordenar (1 aparece primeiro)')),
            ],
            options={
                'verbose_name': 'Membro da Diretoria',
                'verbose_name_plural': 'Membros da Diretoria',
                'ordering': ['tipo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='PaginaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nossa História', max_length=200)),
                ('conteudo', models.TextField(verbose_name='Texto da História')),
                ('frase_destaque', models.CharField(blank=True, max_length=300, verbose_name='Frase de Destaque (Missão)')),
            ],
            options={
                'verbose_name': 'Página Institucional (Texto)',
                'verbose_name_plural': 'Página Institucional (Texto)',
            },
        ),
    ]
