# Generated by Django 5.2.9 on 2026-06-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coluna',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coluna',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
