# Generated by Django 5.2.9 on 2026-06-01 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coluna',
            name='autor',
        ),
        migrations.AddField(
            model_name='coluna',
            name='autor_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Associado (Opcional)'),
        ),
        migrations.AddField(
            model_name='coluna',
            name='instituicao_autor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='coluna',
            name='nome_autor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Autor (Se não for associado)'),
        ),
    ]
