# Generated by Django 5.2.9 on 2026-06-03 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coluna_slug_alter_coluna_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coluna',
            name='autor_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Colunista (Associado/Perfil)'),
        ),
        migrations.AlterField(
            model_name='coluna',
            name='instituicao_autor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instituição (Se for convidado externo)'),
        ),
        migrations.AlterField(
            model_name='coluna',
            name='nome_autor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Autor (Se for convidado externo)'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
