# Generated by Django 5.2.9 on 2026-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_coluna_autor_coluna_autor_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coluna',
            name='resumo',
            field=models.TextField(default='', help_text='Uma breve introdução para atrair o leitor na página inicial.', verbose_name='Resumo'),
            preserve_default=False,
        ),
    ]
