# Generated by Django 5.2.9 on 2025-12-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membrodiretoria_paginainstitucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='instagram/', verbose_name='Imagem do Post')),
                ('link', models.URLField(verbose_name='Link do Post (Instagram)')),
                ('legenda', models.CharField(blank=True, help_text='Texto curto para acessibilidade', max_length=100)),
                ('data_post', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post do Instagram',
                'verbose_name_plural': 'Posts do Instagram (Vitrine)',
                'ordering': ['-data_post'],
            },
        ),
        migrations.AlterModelOptions(
            name='membrodiretoria',
            options={'verbose_name': 'Configuração da Home (Banner/YouTube)', 'verbose_name_plural': 'Configuração da Home (Banner/YouTube)'},
        ),
        migrations.AddField(
            model_name='membrodiretoria',
            name='imagem_banner',
            field=models.ImageField(blank=True, help_text='Imagem de fundo do topo (Opcional)', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='membrodiretoria',
            name='subtitulo_banner',
            field=models.CharField(default='Unindo corações, esclarecendo mentes e consolando almas.', max_length=300),
        ),
        migrations.AddField(
            model_name='membrodiretoria',
            name='titulo_banner',
            field=models.CharField(default='Federação Espírita do Piauí', max_length=200),
        ),
        migrations.AddField(
            model_name='membrodiretoria',
            name='youtube_video_id',
            field=models.CharField(default='SEU_ID_AQUI', help_text='Apenas o código do vídeo (ex: se o link é youtube.com/watch?v=ABC1234, cole ABC1234)', max_length=50),
        ),
    ]
