# Generated by Django 6.0.6 on 2026-06-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_coluna_autor_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrodiretoria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipe/', verbose_name='Foto'),
        ),
    ]
