# Generated by Django 5.2.9 on 2025-12-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postinstagram_alter_membrodiretoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_banner', models.CharField(default='Federação Espírita do Piauí', max_length=200)),
                ('subtitulo_banner', models.CharField(default='Unindo corações, esclarecendo mentes e consolando almas.', max_length=300)),
                ('imagem_banner', models.ImageField(blank=True, help_text='Imagem de fundo do topo (Opcional)', null=True, upload_to='banners/')),
                ('youtube_video_id', models.CharField(default='SEU_ID_AQUI', help_text='Apenas o código do vídeo (ex: se o link é youtube.com/watch?v=ABC1234, cole ABC1234)', max_length=50)),
            ],
            options={
                'verbose_name': 'Configuração da Home (Banner/YouTube)',
                'verbose_name_plural': 'Configuração da Home (Banner/YouTube)',
            },
        ),
    ]
