# Generated by Django 5.2.9 on 2025-12-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracaohome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membrodiretoria',
            options={'ordering': ['tipo', 'ordem'], 'verbose_name': 'Membro da Diretoria', 'verbose_name_plural': 'Membros da Diretoria'},
        ),
        migrations.RemoveField(
            model_name='membrodiretoria',
            name='imagem_banner',
        ),
        migrations.RemoveField(
            model_name='membrodiretoria',
            name='subtitulo_banner',
        ),
        migrations.RemoveField(
            model_name='membrodiretoria',
            name='titulo_banner',
        ),
        migrations.RemoveField(
            model_name='membrodiretoria',
            name='youtube_video_id',
        ),
    ]
