# Generated by Django 5.2.9 on 2026-06-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membrodiretoria_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(default='site.fepi@gmail.com', help_text='E-mail que vai RECEBER as mensagens do Fale Conosco (ex: diretoria@fepi.org.br).', max_length=254, verbose_name='E-mail de Destino (Recebedor)')),
                ('email_remetente', models.EmailField(default='seu_email_fepi@gmail.com', help_text='A conta do Gmail da FEPI usada para ENVIAR as mensagens pelo sistema.', max_length=254, verbose_name='E-mail Remetente (Gmail)')),
                ('senha_app', models.CharField(blank=True, help_text='A senha de 16 letras gerada na segurança do Google (sem espaços).', max_length=50, verbose_name='Senha de Aplicativo (Google)')),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configuração de E-mail',
            },
        ),
    ]
