# Generated by Django 5.2.9 on 2025-12-04 19:17

import django.db.models.deletion
from django.db import migrations, models


# FUNÇÕES DE MIGRATION DE DADOS (NECESSÁRIAS PARA CONVERTER TEXTO PARA ID)
def criar_tipos_e_cargos_base(apps, schema_editor):
    """ Cria os objetos TipoDiretoria e Cargo necessários antes da conversão do campo. """
    TipoDiretoria = apps.get_model('core', 'TipoDiretoria')
    Cargo = apps.get_model('core', 'Cargo')

    # 1. Cria os Tipos de Diretoria (Obrigatoriamente)
    # Estes IDs são necessários para o mapeamento da próxima função.
    TipoDiretoria.objects.bulk_create([
        TipoDiretoria(nome='Diretoria Executiva', ordem=1), 
        TipoDiretoria(nome='Conselho Fiscal', ordem=2),     
        TipoDiretoria(nome='Departamento', ordem=10)        
    ])
    
    # 2. Cria os Cargos Base
    Cargo.objects.bulk_create([
        Cargo(nome='Presidente'),
        Cargo(nome='Vice-Presidente'),
        Cargo(nome='Conselheiro'),
        Cargo(nome='Diretor'),
        Cargo(nome='Responsável')
    ])

def mapear_dados_antigos(apps, schema_editor):
    """ Mapeia os membros existentes para as novas FKs usando os campos temporários. """
    MembroDiretoria = apps.get_model('core', 'MembroDiretoria')
    TipoDiretoria = apps.get_model('core', 'TipoDiretoria')
    Cargo = apps.get_model('core', 'Cargo')
    
    # Pega os IDs base (Presidente e Executiva)
    try:
        executiva = TipoDiretoria.objects.get(nome='Diretoria Executiva')
        presidente = Cargo.objects.get(nome='Presidente')
    except (TipoDiretoria.DoesNotExist, Cargo.DoesNotExist):
        # Não deve acontecer, mas é uma proteção
        return 

    # 1. Mapeia os registros antigos para os NOVOS campos temporários
    MembroDiretoria.objects.all().update(
        tipo_novo=executiva.pk,
        cargo_novo=presidente.pk,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_membrodiretoria_options_and_more'),
    ]

    operations = [
        # 1. CRIAÇÃO DOS MODELOS BASE
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Diretoria/Departamento')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição Breve')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Tipo/Departamento',
                'verbose_name_plural': 'Tipos e Departamentos',
                'ordering': ['ordem'],
            },
        ),
        
        # 2. ADIÇÃO DE CAMPOS NOVOS/TEMPORÁRIOS (Null=True para não falhar)
        migrations.AddField(
            model_name='membrodiretoria',
            name='cargo_novo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, 
                to='core.cargo', 
                verbose_name='Cargo Novo', 
                default=1,
                null=True # Crucial: Permite que exista antes de ser preenchido
            ),
        ),
        migrations.AddField(
            model_name='membrodiretoria',
            name='tipo_novo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, 
                to='core.tipodiretoria', 
                verbose_name='Tipo Novo', 
                default=1,
                null=True # Crucial
            ),
        ),
        
        # 3. INJEÇÃO E MAPEAMENTO DE DADOS
        migrations.RunPython(criar_tipos_e_cargos_base, migrations.RunPython.noop),
        migrations.RunPython(mapear_dados_antigos, migrations.RunPython.noop),

        # 4. ADICIONA CAMPOS DE CONTATO/GESTÃO
        migrations.AddField(
            model_name='membrodiretoria',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='membrodiretoria',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='paginainstitucional',
            name='ano_fim',
            field=models.IntegerField(default=2027, verbose_name='Ano Fim da Gestão'),
        ),
        migrations.AddField(
            model_name='paginainstitucional',
            name='ano_inicio',
            field=models.IntegerField(default=2024, verbose_name='Ano Início da Gestão'),
        ),
        
        # 5. REMOVE CAMPOS ANTIGOS (Texto puro)
        migrations.RemoveField(
            model_name='membrodiretoria',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='membrodiretoria',
            name='tipo',
        ),

        # 6. RENOMEIA CAMPOS TEMPORÁRIOS PARA OS NOMES FINAIS
        migrations.RenameField(
            model_name='membrodiretoria',
            old_name='cargo_novo',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='membrodiretoria',
            old_name='tipo_novo',
            new_name='tipo',
        ),
        
        # 7. AJUSTES FINAIS DE MODELO
        migrations.AlterModelOptions(
            name='membrodiretoria',
            options={'ordering': ['tipo__ordem', 'ordem', 'nome'], 'verbose_name': 'Membro/Responsável', 'verbose_name_plural': 'Membros e Responsáveis'},
        ),
        migrations.AlterField(
            model_name='membrodiretoria',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='membrodiretoria',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Para ordenar dentro do Tipo/Departamento'),
        ),
    ]