# Generated by Django 5.2.9 on 2025-12-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cargo_tipodiretoria_alter_membrodiretoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrodiretoria',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.cargo', verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membrodiretoria',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.tipodiretoria', verbose_name='Tipo/Departamento'),
            preserve_default=False,
        ),
    ]
