# Generated by Django 5.2.9 on 2025-12-10 20:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_membrodiretoria_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginainstitucional',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Texto da História'),
        ),
    ]
