# Generated by Django 5.2.9 on 2025-12-10 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_paginainstitucional_conteudo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaohome',
            options={'verbose_name': 'Configuração da Home (Banner/Pop-up)', 'verbose_name_plural': 'Configuração da Home (Banner/Pop-up)'},
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='popup_ativo',
            field=models.BooleanField(default=False, verbose_name='Ativar Pop-up?'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='popup_botao_texto',
            field=models.CharField(default='Saiba Mais', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='popup_fim',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fim da Exibição'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='popup_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='popup/', verbose_name='Imagem do Pop-up'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='popup_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início da Exibição'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='popup_link',
            field=models.URLField(blank=True, verbose_name='Link de Destino (Notícia/Curso)'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='popup_titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título do Pop-up'),
        ),
    ]
