# Generated by Django 5.2.9 on 2025-12-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_configuracaohome_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nome'], 'verbose_name': 'Cargo Presidência e Departamentos', 'verbose_name_plural': 'Cargos Presidência e Departamentos'},
        ),
    ]
