# Generated by Django 5.2.9 on 2025-12-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cargo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoYouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_mode', models.CharField(choices=[('auto', 'Automático (último do canal)'), ('fixed', 'Fixo (ID informado)'), ('off', 'Desligado')], default='auto', max_length=10, verbose_name='Modo do YouTube')),
                ('youtube_channel_id', models.CharField(blank=True, help_text='Ex: UCxxxx... (ID do canal)', max_length=80, null=True, verbose_name='Channel ID')),
                ('youtube_video_id', models.CharField(blank=True, help_text='Somente o ID do vídeo (ex: ABC1234)', max_length=50, null=True, verbose_name='Video ID (modo fixo)')),
            ],
            options={
                'verbose_name': 'Configuração do YouTube',
                'verbose_name_plural': 'Configuração do YouTube',
            },
        ),
    ]
