# Generated by Django 5.2.9 on 2025-12-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuracaoyoutube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaohome',
            name='youtube_video_id',
        ),
    ]
