# Generated by Django 5.2.9 on 2025-12-27 02:08

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_configuracaohome_youtube_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, verbose_name='Dia da Semana')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Atividade')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição Curta')),
                ('publico_alvo', models.CharField(default='Público Geral', max_length=100)),
            ],
            options={
                'verbose_name': 'Atividade Semanal',
                'verbose_name_plural': 'Atividades Semanais (Grade Fixa)',
                'ordering': ['dia', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Evento')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug (URL)')),
                ('data_inicio', models.DateTimeField(verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('local', models.CharField(default='Auditório da FEPI', max_length=200)),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Detalhes do Evento')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Banner/Cartaz')),
                ('link_inscricao', models.URLField(blank=True, null=True, verbose_name='Link de Inscrição')),
                ('valor', models.CharField(blank=True, help_text='Ex: Gratuito ou R$ 20,00', max_length=50, verbose_name='Valor (se houver)')),
                ('destaque_home', models.BooleanField(default=False, verbose_name='Destacar na Home?')),
            ],
            options={
                'verbose_name': 'Evento / Curso',
                'verbose_name_plural': 'Agenda de Eventos e Cursos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Notícia')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Resumo / Subtítulo')),
                ('conteudo', ckeditor.fields.RichTextField(verbose_name='Conteúdo Completo')),
                ('autor', models.CharField(default='Assessoria FEPI', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug (URL Amigável)')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem de Capa')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='PalestraPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Horário')),
                ('tema', models.CharField(max_length=200, verbose_name='Tema da Palestra')),
                ('orador', models.CharField(max_length=150, verbose_name='Orador / Expositor')),
                ('casa_espirita', models.CharField(blank=True, help_text='Deixar em branco se for da casa', max_length=150, verbose_name='Casa Espírita (Origem)')),
                ('imagem_divulgacao', models.ImageField(blank=True, null=True, upload_to='palestras/', verbose_name='Cartaz de Divulgação')),
                ('link_transmissao', models.URLField(blank=True, null=True, verbose_name='Link YouTube (se houver)')),
            ],
            options={
                'verbose_name': 'Palestra Pública',
                'verbose_name_plural': 'Agenda de Palestras',
                'ordering': ['-data_hora'],
            },
        ),
    ]
