# Generated by Django 5.2.9 on 2025-12-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_livro_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('BASICAS', 'Obras Básicas (Kardec)'), ('ROMANCE', 'Romance'), ('ESTUDO', 'Estudo / Filosófico'), ('INFANTIL', 'Infantil / Juvenil'), ('MEDIUNIDADE', 'Mediunidade'), ('MENSAGENS', 'Mensagens / Consolo'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria'),
        ),
    ]
