# Generated by Django 5.2.9 on 2025-12-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_alter_livro_options_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='codigo',
            field=models.CharField(default='0000', max_length=20, verbose_name='Código / ISBN'),
        ),
    ]
