# Generated by Django 5.2.9 on 2025-12-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0006_livro_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivrariaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='livraria_config/', verbose_name='Logo da Livraria (Branding)')),
                ('instagram_widget_code', models.TextField(blank=True, verbose_name='Código do Widget do Instagram (SnapWidget)')),
            ],
            options={
                'verbose_name': 'Configuração da Livraria',
                'verbose_name_plural': 'Configuração da Livraria',
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='destaque_home',
            field=models.BooleanField(default=False, verbose_name='Destaque Rotativo na Home'),
        ),
    ]
