# Generated by Django 5.2.9 on 2025-12-12 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0007_livrariaconfig_livro_destaque_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
