# Generated by Django 5.2.9 on 2025-12-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0008_alter_livro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Link Amigável'),
        ),
    ]
