# Generated by Django 5.2.9 on 2025-12-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0009_livro_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='livrariaconfig',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Ex: https://www.instagram.com/livrariaramirogama', null=True, verbose_name='Link do Perfil do Instagram'),
        ),
        migrations.AddField(
            model_name='livrariaconfig',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Digite apenas números, com DDD. Ex: 5535999887766', max_length=20, null=True, verbose_name='WhatsApp de Vendas'),
        ),
    ]
