# Generated by Django 5.2.9 on 2026-08-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0010_livrariaconfig_instagram_url_livrariaconfig_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoLivraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('editora', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto da Livraria',
                'verbose_name_plural': 'Produtos da Livraria',
            },
        ),
    ]
