# Generated by Django 5.2.9 on 2026-08-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0012_historicouploadprodutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ativo_na_vitrine',
            field=models.BooleanField(default=True, verbose_name='Ativo na vitrine'),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_estoque',
            field=models.IntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
        migrations.AddField(
            model_name='livro',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='codigo',
            field=models.CharField(db_index=True, default='0000', max_length=50, verbose_name='Código / ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=False, verbose_name='Disponível para venda'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
