# Generated by Django 5.2.9 on 2025-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.TextField(help_text='Um texto curto para chamar a atenção na página inicial.', verbose_name='Resumo (para a capa)')),
                ('conteudo', models.TextField(verbose_name='Conteúdo Completo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem de Destaque')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
