# Generated by Django 5.2.9 on 2025-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='FEPI', max_length=100, verbose_name='Autor da Publicação'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='foi_publicada',
            field=models.BooleanField(default=True, verbose_name='Publicada no Site'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_capas/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumo',
            field=models.TextField(blank=True, verbose_name='Resumo (para lista)'),
        ),
    ]
