# Generated by Django 5.2.9 on 2025-12-10 20:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_autor_noticia_foi_publicada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
