# Generated by Django 5.2.9 on 2025-12-12 18:33

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='foi_publicada',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='resumo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug / Link Amigável'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='FEPI', max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo da Notícia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem de Capa'),
        ),
    ]
