# Generated by Django 5.2.9 on 2025-12-12 19:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_remove_noticia_foi_publicada_remove_noticia_resumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumo',
            field=models.TextField(blank=True, help_text='Um texto curto para chamar a atenção.', max_length=500, verbose_name='Resumo (Aparece na lista)'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo Completo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
