# Generated by Django 5.2.9 on 2026-06-15 16:02

import ckeditor.fields
import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticia_resumo_alter_noticia_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='conteudo_blocos',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Conteúdo da Notícia (Editor Moderno)'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Conteúdo Antigo (Não preencher em novas notícias)'),
        ),
    ]
