# Generated by Django 5.2.9 on 2025-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Centro')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço Completo')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(default='Teresina', max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/WhatsApp')),
                ('tipo', models.CharField(choices=[('CAPITAL', 'Capital (Teresina)'), ('INTERIOR', 'Interior do Estado'), ('ESPECIALIZADA', 'Entidade Especializada')], default='CAPITAL', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='centros/', verbose_name='Foto ou Logo')),
            ],
            options={
                'verbose_name': 'Centro Espírita',
                'verbose_name_plural': 'Centros Espíritas',
                'ordering': ['cidade', 'nome'],
            },
        ),
    ]
