# Generated by Django 5.2.9 on 2025-12-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='centro',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Formato: XX.XXX.XXX/0001-XX', max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='centro',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='centro',
            name='data_fundacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fundação'),
        ),
        migrations.AddField(
            model_name='centro',
            name='estado',
            field=models.CharField(choices=[('PI', 'Piauí'), ('MA', 'Maranhão'), ('CE', 'Ceará')], default='PI', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='centro',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='centro',
            name='site',
            field=models.URLField(blank=True, help_text='Cole o link completo (https://...)', null=True, verbose_name='Site ou Instagram'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centro',
            name='endereco',
            field=models.CharField(max_length=300, verbose_name='Logradouro (Rua, Av...)'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='centros/', verbose_name='Logo/Foto'),
        ),
    ]
