# Generated by Django 5.2.9 on 2025-12-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_centro_cep_centro_cnpj_centro_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='endereco',
            field=models.CharField(max_length=300, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='estado',
            field=models.CharField(choices=[('PI', 'Piauí'), ('MA', 'Maranhão'), ('CE', 'Ceará')], default='PI', max_length=2),
        ),
        migrations.AlterField(
            model_name='centro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='centros/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site ou Instagram'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
