# Generated by Django 5.2.9 on 2026-06-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0003_alter_centro_cep_alter_centro_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='latitude',
            field=models.CharField(blank=True, help_text='Obrigatório para aparecer no mapa. Ex: -5.08921', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='centro',
            name='longitude',
            field=models.CharField(blank=True, help_text='Ex: -42.8016', max_length=50, null=True),
        ),
    ]
