# Generated by Django 5.2.9 on 2026-06-09 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Departamento de Infância e Juventude (DIJE)', max_length=100, verbose_name='Nome do Departamento')),
                ('subdominio', models.CharField(help_text="Ex: 'dije' (o link ficará dije.fepi.org.br)", max_length=50, unique=True)),
                ('cor_primaria', models.CharField(default='#0056b3', help_text='Cor principal em HEX (para personalizar o template)', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='blogs/logos/')),
                ('descricao', models.TextField(blank=True, help_text='Pequeno texto sobre o departamento')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog de Departamento',
                'verbose_name_plural': 'Blogs de Departamentos',
            },
        ),
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('resumo', models.TextField(blank=True, help_text='Aparece na lista de postagens do blog', max_length=500)),
                ('conteudo', models.TextField(help_text='Conteúdo completo (usará o CKEditor no painel)')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='blogs/capas/')),
                ('nome_autor_externo', models.CharField(blank=True, help_text='Preencher caso o autor não tenha conta no sistema', max_length=100)),
                ('data_publicacao', models.DateTimeField()),
                ('publicado', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.blogdepartamento')),
            ],
            options={
                'verbose_name': 'Postagem do Blog',
                'verbose_name_plural': 'Postagens dos Blogs',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
