# Generated by Django 5.2.9 on 2026-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdepartamento',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Ex: https://instagram.com/dije_fepi', null=True, verbose_name='URL do Instagram'),
        ),
        migrations.AddField(
            model_name='blogdepartamento',
            name='instagram_widget_code',
            field=models.TextField(blank=True, help_text='Cole aqui o código embed/iframe obtido em ferramentas gratuitas', null=True, verbose_name='Código do Widget do Instagram'),
        ),
        migrations.AlterField(
            model_name='blogdepartamento',
            name='cor_primaria',
            field=models.CharField(default='#008080', help_text='Cor principal em HEX (para personalizar o template)', max_length=7),
        ),
        migrations.AlterField(
            model_name='blogdepartamento',
            name='subdominio',
            field=models.CharField(help_text="Ex: 'dije' (o link ficará dije.fepiaui.org.br)", max_length=50, unique=True),
        ),
    ]
