# Generated by Django 5.2.9 on 2026-06-22 18:53

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogdepartamento_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='conteudo',
            field=django_editorjs_fields.fields.EditorJsJSONField(verbose_name='Conteúdo do Artigo'),
        ),
    ]
