# Generated by Django 5.2.9 on 2026-06-22 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_postblog_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('cor', models.CharField(default='#7f8c8d', help_text='Cor da tag em HEX (ex: #3498db)', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria do Blog',
                'verbose_name_plural': 'Categorias dos Blogs',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='postblog',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blogs.categoriablog', verbose_name='Categoria / Tag'),
        ),
    ]
