# Generated by Django 5.2.9 on 2026-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_categoriablog_postblog_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo do Artigo'),
        ),
    ]
