# Generated by Django 5.2.9 on 2026-08-26 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copiar_vinculos_legados(apps, schema_editor):
    Perfil = apps.get_model('usuarios', 'Perfil')
    BlogMembro = apps.get_model('blogs', 'BlogMembro')
    for perfil in Perfil.objects.exclude(departamento_blog_id=None).iterator():
        BlogMembro.objects.get_or_create(
            usuario_id=perfil.user_id,
            blog_id=perfil.departamento_blog_id,
            defaults={'papel': 'editor', 'ativo': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_postblog_conteudo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0004_perfil_departamento_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('editor', 'Editor'), ('revisor', 'Revisor'), ('gestor', 'Gestor')], default='editor', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='blogs.blogdepartamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_de_blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro de Blog',
                'verbose_name_plural': 'Membros de Blogs',
                'ordering': ['blog__nome', 'usuario__username'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'blog'), name='unique_usuario_blog')],
            },
        ),
        migrations.RunPython(copiar_vinculos_legados, migrations.RunPython.noop),
    ]
