# Generated by Django 5.2.9 on 2026-08-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blogmembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdepartamento',
            name='cor_secundaria',
            field=models.CharField(default='#d6ad55', help_text='Cor secundária em HEX', max_length=7),
        ),
        migrations.AddField(
            model_name='blogdepartamento',
            name='frase_destaque',
            field=models.CharField(blank=True, help_text='Frase exibida no destaque do blog', max_length=180),
        ),
        migrations.AddField(
            model_name='blogdepartamento',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/banners/'),
        ),
        migrations.AddField(
            model_name='blogdepartamento',
            name='tema',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('institucional', 'Institucional'), ('agenda', 'Agenda e notícias')], default='editorial', max_length=20),
        ),
    ]
