# Generated by Django 5.2.9 on 2026-03-18 12:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Voluntário')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=50, null=True, verbose_name='RG/Exp.')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('cidade_estado', models.CharField(blank=True, default='Teresina/PI', max_length=100, null=True, verbose_name='Cidade/Estado')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone(s)')),
                ('atividade_profissional', models.CharField(blank=True, max_length=200, null=True, verbose_name='Atividade Profissional')),
                ('tipo_servico', models.TextField(blank=True, null=True, verbose_name='Tipo de Serviço a prestar')),
                ('dias_horarios', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dia(s) / Horário(s)')),
                ('termo_assinado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='termo_pdf')),
                ('certidao_antecedentes', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certidao_pdf')),
                ('data_ultima_certidao', models.DateField(blank=True, null=True, verbose_name='Data da última certidão')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voluntários',
            },
        ),
    ]
