# Generated by Django 5.2.9 on 2026-03-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='prazo_determinado',
            field=models.DateField(blank=True, help_text='Ex: Fevereiro de 2027', null=True, verbose_name='Prazo do Termo'),
        ),
    ]
