# Generated by Django 5.2.9 on 2026-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_voluntario_prazo_determinado'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro (Rua/Av)'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='prazo_determinado',
            field=models.DateField(blank=True, help_text='Data final da vigência', null=True, verbose_name='Prazo do Termo'),
        ),
    ]
