# Generated by Django 5.2.9 on 2026-03-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0003_voluntario_bairro_voluntario_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='prazo_determinado',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
    ]
