# Generated by Django 5.2.9 on 2026-03-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0004_remove_voluntario_prazo_determinado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={},
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='certidao_antecedentes',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='data_ultima_certidao',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='termo_assinado',
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.CreateModel(
            name='DocumentoVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Termo', 'Termo de Adesão Assinado'), ('Certidao', 'Certidão de Antecedentes'), ('Outro', 'Outro Documento')], max_length=50, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='voluntarios/historico/')),
                ('data_referencia', models.DateField(verbose_name='Data do Documento (Emissão)')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='voluntarios.voluntario')),
            ],
            options={
                'ordering': ['-data_referencia'],
            },
        ),
    ]
