# Generated by Django 5.2.9 on 2026-03-18 14:44

import ckeditor.fields
import intranet.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0005_alter_voluntario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloTermoVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', ckeditor.fields.RichTextField(help_text='Use as tags disponíveis para puxar os dados do voluntário.', verbose_name='Corpo do Termo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo do Termo de Voluntário',
            },
        ),
        migrations.AlterField(
            model_name='documentovoluntario',
            name='arquivo',
            field=models.FileField(storage=intranet.storage.SignedRawMediaCloudinaryStorage(), upload_to='voluntarios/historico/'),
        ),
    ]
