# Generated by Django 5.2.9 on 2026-06-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_options_perfil_atividade_profissional_and_more'),
        ('voluntarios', '0006_modelotermovoluntario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentovoluntario',
            name='voluntario',
            field=models.ForeignKey(limit_choices_to={'is_voluntario': True}, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_voluntario', to='usuarios.perfil', verbose_name='Voluntário'),
        ),
        migrations.AlterModelOptions(
            name='documentovoluntario',
            options={'ordering': ['-data_referencia'], 'verbose_name': 'Documento de Voluntário', 'verbose_name_plural': 'Documentos de Voluntários'},
        ),
        migrations.DeleteModel(
            name='Voluntario',
        ),
    ]
