# Generated by Django 5.2.9 on 2026-08-25 18:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0007_alter_documentovoluntario_voluntario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelotermovoluntario',
            name='conteudo',
            field=ckeditor.fields.RichTextField(help_text='Use as tags disponíveis para puxar os dados do voluntário (ex: {{ voluntario.nome }}, {{ dia }}, {{ mes_nome }}, {{ ano }}).', verbose_name='Corpo do Termo'),
        ),
    ]
