# Generated by Django 5.2.9 on 2026-06-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil Único', 'verbose_name_plural': 'Perfis Únicos'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='atividade_profissional',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Atividade Profissional'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_inicio_voluntariado',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início no Voluntariado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_termino_voluntariado',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término no Voluntariado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dias_horarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dia(s) / Horário(s) Disponíveis'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='autores_perfis/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_voluntario',
            field=models.BooleanField(default=False, verbose_name='É Voluntário?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RG/Exp.'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_servico',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de Serviço a prestar'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone(s)/WhatsApp'),
        ),
    ]
