# Generated by Django 5.2.9 on 2026-06-13 13:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_options_perfil_atividade_profissional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaSejaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Escreva aqui o texto convidativo. Se deixar em branco, o texto padrão será exibido.', null=True, verbose_name='Conteúdo da Página (História e Motivos)')),
            ],
            options={
                'verbose_name': 'Página Seja Membro',
                'verbose_name_plural': 'Página Seja Membro',
            },
        ),
    ]
