# Generated by Django 5.2.9 on 2026-06-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_categoriablog_postblog_categoria'),
        ('usuarios', '0003_paginasejamembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='departamento_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_editores', to='blogs.blogdepartamento', verbose_name='Editor do Blog (Departamento)'),
        ),
    ]
