"""
Django settings for fepi_site project.
Generated by 'django-admin startproject' using Django 5.2.9.
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET_KEY
# Tenta pegar do ambiente (Render) ou usa uma padrão insegura para local
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-#up2mw6n4z7=cl@*$c$y@!!la*(*-!idc+0y_dabnogc$2zjj(')

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')

# --------------------------------------------------------
# 🚀 SEGURANÇA GLOBAL - CSRF E HOSTS
# --------------------------------------------------------
# Colocamos fora do if/else para garantir que o Django SEMPRE 
# reconheça os domínios, mesmo se a variável de ambiente falhar.

CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://*.up.railway.app', 
    'https://fepiaui.org.br', 
    'https://www.fepiaui.org.br',
    'https://fepiaui.cewantuildefreitas.com.br',
    'https://fepi.cewantuildefreitas.com.br'
]

# --------------------------------------------------------
# 🚀 Configuração Dinâmica de Ambientes (Render)
# --------------------------------------------------------

# O Render injeta automaticamente a variável 'RENDER' no ambiente de produção
IS_RENDER_PROD = 'RENDER' in os.environ

if IS_RENDER_PROD:
    # MODO PRODUÇÃO (RENDER)
    DEBUG = False
    
    ALLOWED_HOSTS = [
        'fepiaui.org.br', 
        'www.fepiaui.org.br',
        'fepiaui.cewantuildefreitas.com.br', 
        'fepi.cewantuildefreitas.com.br'     
    ]

    # O Render fornece o domínio da aplicação dinamicamente
    RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    else:
        ALLOWED_HOSTS.append('*')
    
    # Conexão com o Banco de Dados do Render
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

    # Segurança HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

else:
    # MODO DESENVOLVIMENTO (Local)
    DEBUG = True 
    # Garantimos os domínios aqui também caso o Render rode como local
    ALLOWED_HOSTS = ['*', 'fepi.cewantuildefreitas.com.br', 'fepiaui.cewantuildefreitas.com.br'] 
    
    # Se passarmos o link do banco no terminal, liga-se à nuvem (Render)
    # Se não passarmos nada, usa o banco SQLite local vazio para testes isolados
    if 'DATABASE_URL' in os.environ:
        DATABASES = {
            'default': dj_database_url.config(
                default=os.environ.get('DATABASE_URL'),
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'django.contrib.humanize',
    # Minhas Apps
    'core',
    'livraria',
    'noticias',
    'centros',
    'programacao',
    'recursos',
    'doacoes',
    'intranet', 
    # Libs
    'ckeditor',
    'ckeditor_uploader',
    'voluntarios',
    'painel',
    'usuarios',
    'blogs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise para CSS e ficheiros estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fepi_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_wide_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'fepi_site.wsgi.application'


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# --- ARQUIVOS ESTÁTICOS (CSS, JS, Logos) ---
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' 
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Configure static file finders to ensure collectstatic finds all files
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# --- ARQUIVOS DE MÍDIA (FOTOS, PDFs) ---
MEDIA_URL = '/media/' 
MEDIA_ROOT = BASE_DIR / 'media' 

# 1. Configuração para o Storage do Django (que você já tinha)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dym1yoj68',
    'API_KEY': '283348431723888',
    'API_SECRET': 'PRLSa_vmaDRFTE0TJnDBsec-N24',
}

# 2. NOVA CONFIGURAÇÃO: Exigida pelo 'CloudinaryField' direto
CLOUDINARY = {
    'cloud_name': 'dym1yoj68',
    'api_key': '283348431723888',
    'api_secret': 'PRLSa_vmaDRFTE0TJnDBsec-N24',
}

# --- CONFIGURAÇÃO DEFINITIVA DE STORAGES ---
# Usamos a versão simples do WhiteNoise para não travar com o CKEditor
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}

# Compatibilidade forçada para bibliotecas antigas
STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'

# Opcional: Diga ao WhiteNoise para usar nomes de arquivo imutáveis
WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: ('.' in url and url.rsplit('.', 1)[1] in ['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'css', 'js', 'woff', 'woff2', 'ttf', 'eot'])

# --- CONFIGURAÇÕES DO CKEDITOR ---
CKEDITOR_UPLOAD_PATH = "uploads/ckeditor/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['Image', 'Iframe', 'Table', 'HorizontalRule'], # <--- BOTÕES MÁGICOS AQUI
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'Source']
        ],
        'width': '100%',
        'height': 400,
        'toolbarCanCollapse': False,
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Email
EMAIL_RECEIVER = 'contato@fepiaui.org.br' 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'seu_email_remetente@gmail.com') 
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'sua_senha_de_app_aqui') 
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Login
LOGIN_URL = 'login'                
LOGIN_REDIRECT_URL = 'area_federado' 
LOGOUT_REDIRECT_URL = 'home'

# Impede que o WhiteNoise trave o deploy caso alguma biblioteca de terceiros (como o CKEditor) 
# tenha links quebrados de imagens dentro dos seus arquivos CSS.
WHITENOISE_MANIFEST_STRICT = False

SITE_ID = 1