"""
Django settings for fepi_site project.
Generated by 'django-admin startproject' using Django 5.2.9.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET_KEY
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-#up2mw6n4z7=cl@*$c$y@!!la*(*-!idc+0y_dabnogc$2zjj(')

# --------------------------------------------------------
# 🚀 Configuração Dinâmica de Ambientes (DEBUG, HOSTS, DB)
# --------------------------------------------------------

# Verifica se a variável de ambiente DATABASE_URL existe (só existirá no Railway)
IS_RAILWAY_PROD = 'DATABASE_URL' in os.environ

if IS_RAILWAY_PROD:
    # MODO PRODUÇÃO (RAILWAY - PostgreSQL)
    DEBUG = False
    
    ALLOWED_HOSTS = [
        '127.0.0.1', 
        '.railway.app', 
        'localhost', 
        'seusitedjango.railway.app', 
        'mauriciobts.pythonanywhere.com' 
    ]
    
    # DATABASES: Usa PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

    # --- CONFIGURAÇÕES DE SEGURANÇA (HTTPS / SSL) ---
    # Isto garante que o Django sabe que está em HTTPS e carrega as imagens no WhatsApp
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Lista de domínios confiáveis para evitar erro 403 Forbidden no Login
    CSRF_TRUSTED_ORIGINS = ['https://mauriciobts.pythonanywhere.com', 'https://seusitedjango.railway.app']

else:
    # MODO DESENVOLVIMENTO (Local - SQLite)
    DEBUG = True 
    ALLOWED_HOSTS = ['*'] 
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Minhas Apps
    'core',
    'livraria',
    'noticias',
    'centros',
    'programacao',
    'recursos',
    'doacoes',
    'intranet', # <--- APP DA INTRANET
    # Libs
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fepi_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'], # Garante que ache a pasta registration
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_wide_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'fepi_site.wsgi.application'


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' 
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# ----------------------------------------------------
# CONFIGURAÇÃO DE EMAIL
# ----------------------------------------------------
EMAIL_RECEIVER = 'contato@fepiaui.org.br' 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'seu_email_remetente@gmail.com') 
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'sua_senha_de_app_aqui') 
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# --- CONFIGURAÇÃO DE LOGIN / INTRANET ---
LOGIN_URL = 'login'               # Nome da rota de login
LOGIN_REDIRECT_URL = 'area_federado' # Para onde vai depois de logar
LOGOUT_REDIRECT_URL = 'home'      # Para onde vai depois de sair