# Generated by Django 5.2.9 on 2026-08-27 01:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdesaoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de ativação'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('inadimplente', 'Inadimplente'), ('cancelada', 'Cancelada'), ('encerrada', 'Encerrada')], default='pendente', max_length=20, verbose_name='Situação')),
                ('forma_pagamento', models.CharField(choices=[('cartao', 'Cartão de crédito'), ('boleto', 'Boleto bancário'), ('pix', 'Pix')], max_length=20, verbose_name='Forma de pagamento')),
                ('valor_contratado', models.DecimalField(decimal_places=2, help_text='Snapshot do valor no momento da adesão.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor contratado')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Dia de vencimento')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Início da adesão')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim da adesão')),
                ('proxima_cobranca', models.DateField(blank=True, null=True, verbose_name='Próxima cobrança')),
                ('gateway', models.CharField(choices=[('nenhum', 'Ainda não definido'), ('pagbank', 'PagBank'), ('pagarme', 'Pagar.me')], default='nenhum', max_length=20, verbose_name='Gateway utilizado')),
                ('gateway_customer_id', models.CharField(blank=True, max_length=120, verbose_name='ID do cliente no gateway')),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=120, verbose_name='ID da assinatura no gateway')),
                ('gateway_reference', models.CharField(blank=True, max_length=150, verbose_name='Referência externa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('federado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesoes_mensalidade', to=settings.AUTH_USER_MODEL, verbose_name='Federado')),
            ],
            options={
                'verbose_name': 'Adesão de mensalidade',
                'verbose_name_plural': 'Adesões de mensalidade',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês de referência, por exemplo 2026-08-01.', verbose_name='Competência')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da cobrança')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando pagamento'), ('processando', 'Processando'), ('pago', 'Pago'), ('vencida', 'Vencida'), ('falha', 'Falha no pagamento'), ('cancelada', 'Cancelada'), ('estornada', 'Estornada'), ('conciliacao_manual', 'Conciliação manual')], default='pendente', max_length=25, verbose_name='Situação')),
                ('forma_pagamento', models.CharField(choices=[('cartao', 'Cartão de crédito'), ('boleto', 'Boleto bancário'), ('pix', 'Pix')], max_length=20, verbose_name='Forma de pagamento')),
                ('gateway', models.CharField(choices=[('nenhum', 'Ainda não definido'), ('pagbank', 'PagBank'), ('pagarme', 'Pagar.me')], default='nenhum', max_length=20, verbose_name='Gateway')),
                ('gateway_invoice_id', models.CharField(blank=True, max_length=120, verbose_name='ID da fatura no gateway')),
                ('gateway_charge_id', models.CharField(blank=True, max_length=120, verbose_name='ID da cobrança no gateway')),
                ('url_pagamento', models.URLField(blank=True, verbose_name='URL de pagamento')),
                ('url_boleto', models.URLField(blank=True, verbose_name='URL do boleto')),
                ('codigo_barras', models.CharField(blank=True, max_length=250, verbose_name='Código de barras')),
                ('pix_copia_cola', models.TextField(blank=True, verbose_name='Pix copia e cola')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('dados_gateway', models.JSONField(blank=True, default=dict, verbose_name='Dados não sensíveis do gateway')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('adesao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='financeiro.adesaomensalidade', verbose_name='Adesão')),
            ],
            options={
                'verbose_name': 'Cobrança de mensalidade',
                'verbose_name_plural': 'Cobranças de mensalidade',
                'ordering': ['-competencia', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('nenhum', 'Ainda não definido'), ('pagbank', 'PagBank'), ('pagarme', 'Pagar.me')], max_length=20, verbose_name='Gateway')),
                ('evento_id', models.CharField(max_length=160, verbose_name='ID do evento no gateway')),
                ('tipo_evento', models.CharField(max_length=120, verbose_name='Tipo do evento')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('processado', 'Processado'), ('erro', 'Erro no processamento'), ('ignorado', 'Ignorado')], default='recebido', max_length=20, verbose_name='Processamento')),
                ('assinatura_validada', models.BooleanField(default=False, verbose_name='Assinatura validada')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload recebido')),
                ('ocorrido_em', models.DateTimeField(blank=True, null=True, verbose_name='Ocorrido em')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas de processamento')),
                ('erro_processamento', models.TextField(blank=True, verbose_name='Erro de processamento')),
                ('adesao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_gateway', to='financeiro.adesaomensalidade', verbose_name='Adesão relacionada')),
                ('cobranca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_gateway', to='financeiro.cobrancamensalidade', verbose_name='Cobrança relacionada')),
            ],
            options={
                'verbose_name': 'Evento de gateway',
                'verbose_name_plural': 'Eventos de gateway',
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativa', models.PositiveSmallIntegerField(default=1, verbose_name='Número da tentativa')),
                ('gateway', models.CharField(choices=[('nenhum', 'Ainda não definido'), ('pagbank', 'PagBank'), ('pagarme', 'Pagar.me')], max_length=20, verbose_name='Gateway')),
                ('forma_pagamento', models.CharField(choices=[('cartao', 'Cartão de crédito'), ('boleto', 'Boleto bancário'), ('pix', 'Pix')], max_length=20, verbose_name='Forma de pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('autorizado', 'Autorizado'), ('pago', 'Pago'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], default='pendente', max_length=20, verbose_name='Situação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor pago/tentado')),
                ('gateway_payment_id', models.CharField(blank=True, max_length=120, verbose_name='ID do pagamento no gateway')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=120, verbose_name='ID da transação no gateway')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('falhou_em', models.DateTimeField(blank=True, null=True, verbose_name='Falhou em')),
                ('motivo_falha', models.TextField(blank=True, verbose_name='Motivo da falha')),
                ('dados_gateway', models.JSONField(blank=True, default=dict, verbose_name='Dados não sensíveis do gateway')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.cobrancamensalidade', verbose_name='Cobrança')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Código estável usado nas integrações e URLs internas.', max_length=80, unique=True, verbose_name='Identificador interno')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do plano')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da mensalidade')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, help_text='Use de 1 a 28 para evitar ambiguidades em fevereiro.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Dia de vencimento')),
                ('gateway', models.CharField(choices=[('nenhum', 'Ainda não definido'), ('pagbank', 'PagBank'), ('pagarme', 'Pagar.me')], default='nenhum', max_length=20, verbose_name='Gateway')),
                ('gateway_plan_id', models.CharField(blank=True, help_text='Preenchido somente após criação e homologação no gateway.', max_length=120, verbose_name='ID do plano no gateway')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de mensalidade',
                'verbose_name_plural': 'Planos de mensalidade',
                'ordering': ['nome'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='plano_mens_valor_nneg'), models.CheckConstraint(condition=models.Q(('dia_vencimento__gte', 1), ('dia_vencimento__lte', 28)), name='plano_mens_dia_1_28'), models.UniqueConstraint(condition=models.Q(('gateway_plan_id', ''), _negated=True), fields=('gateway', 'gateway_plan_id'), name='plano_mens_gateway_id')],
            },
        ),
        migrations.AddField(
            model_name='adesaomensalidade',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesoes', to='financeiro.planomensalidade', verbose_name='Plano'),
        ),
        migrations.CreateModel(
            name='AuditoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('alteracao', 'Alteração'), ('ativacao', 'Ativação'), ('suspensao', 'Suspensão'), ('cancelamento', 'Cancelamento'), ('baixa_manual', 'Baixa manual'), ('conciliacao', 'Conciliação'), ('estorno', 'Estorno'), ('outro', 'Outra ação')], max_length=25, verbose_name='Ação')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID do objeto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict, verbose_name='Dados anteriores')),
                ('dados_novos', models.JSONField(blank=True, default=dict, verbose_name='Dados novos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Tipo do objeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_financeiras', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'verbose_name': 'Auditoria financeira',
                'verbose_name_plural': 'Auditorias financeiras',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_objeto_idx'), models.Index(fields=['acao', 'criado_em'], name='audit_acao_data_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cobrancamensalidade',
            index=models.Index(fields=['status', 'vencimento'], name='cobr_status_venc_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancamensalidade',
            index=models.Index(fields=['adesao', 'competencia'], name='cobr_adesao_comp_idx'),
        ),
        migrations.AddConstraint(
            model_name='cobrancamensalidade',
            constraint=models.UniqueConstraint(fields=('adesao', 'competencia'), name='cobranca_mens_competencia'),
        ),
        migrations.AddConstraint(
            model_name='cobrancamensalidade',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='cobranca_mens_valor_nneg'),
        ),
        migrations.AddConstraint(
            model_name='cobrancamensalidade',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_invoice_id', ''), _negated=True), fields=('gateway', 'gateway_invoice_id'), name='cobranca_mens_gateway_inv'),
        ),
        migrations.AddConstraint(
            model_name='cobrancamensalidade',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_charge_id', ''), _negated=True), fields=('gateway', 'gateway_charge_id'), name='cobranca_mens_gateway_chg'),
        ),
        migrations.AddIndex(
            model_name='eventogateway',
            index=models.Index(fields=['gateway', 'status'], name='evt_gateway_status_idx'),
        ),
        migrations.AddIndex(
            model_name='eventogateway',
            index=models.Index(fields=['tipo_evento', 'recebido_em'], name='evt_tipo_recebido_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventogateway',
            constraint=models.UniqueConstraint(fields=('gateway', 'evento_id'), name='evento_gateway_evento_id'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['cobranca', 'status'], name='pag_cobr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['gateway', 'status'], name='pag_gateway_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='pagamento_valor_nneg'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_payment_id', ''), _negated=True), fields=('gateway', 'gateway_payment_id'), name='pag_gateway_payment_id'),
        ),
        migrations.AddIndex(
            model_name='adesaomensalidade',
            index=models.Index(fields=['federado', 'status'], name='adesao_fed_status_idx'),
        ),
        migrations.AddIndex(
            model_name='adesaomensalidade',
            index=models.Index(fields=['plano', 'status'], name='adesao_plano_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='adesaomensalidade',
            constraint=models.CheckConstraint(condition=models.Q(('valor_contratado__gte', 0)), name='adesao_mens_valor_nneg'),
        ),
        migrations.AddConstraint(
            model_name='adesaomensalidade',
            constraint=models.CheckConstraint(condition=models.Q(('dia_vencimento__gte', 1), ('dia_vencimento__lte', 28)), name='adesao_mens_dia_1_28'),
        ),
        migrations.AddConstraint(
            model_name='adesaomensalidade',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='adesao_mens_datas_validas'),
        ),
        migrations.AddConstraint(
            model_name='adesaomensalidade',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_subscription_id', ''), _negated=True), fields=('gateway', 'gateway_subscription_id'), name='adesao_mens_gateway_sub'),
        ),
    ]
