# Generated by Django 5.2.9 on 2026-08-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancamensalidade',
            name='documento_pagador',
            field=models.CharField(blank=True, max_length=18, verbose_name='Documento do pagador na cobrança'),
        ),
        migrations.AddField(
            model_name='cobrancamensalidade',
            name='email_pagador',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do pagador na cobrança'),
        ),
        migrations.AddField(
            model_name='cobrancamensalidade',
            name='nome_pagador',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do pagador na cobrança'),
        ),
        migrations.AddField(
            model_name='cobrancamensalidade',
            name='pix_expira_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Pix'),
        ),
        migrations.AddField(
            model_name='cobrancamensalidade',
            name='telefone_pagador',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone do pagador na cobrança'),
        ),
    ]
