# Generated by Django 5.2.9 on 2026-08-27 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_cobrancamensalidade_documento_pagador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('gateway', models.CharField(choices=[('nenhum', 'Ainda não definido'), ('pagbank', 'PagBank'), ('pagarme', 'Pagar.me')], default='nenhum', max_length=20, verbose_name='Gateway ativo')),
                ('ambiente', models.CharField(choices=[('sandbox', 'Sandbox / testes'), ('producao', 'Produção')], default='sandbox', max_length=20, verbose_name='Ambiente')),
                ('ativo', models.BooleanField(default=False, help_text='Ative somente depois de configurar e homologar as credenciais no ambiente da aplicação.', verbose_name='Integração ativa')),
                ('aceita_cartao', models.BooleanField(default=True, verbose_name='Aceita cartão')),
                ('aceita_boleto', models.BooleanField(default=True, verbose_name='Aceita boleto')),
                ('aceita_pix', models.BooleanField(default=True, verbose_name='Aceita Pix')),
                ('webhook_url', models.URLField(blank=True, help_text='Endpoint público que receberá atualizações do gateway quando a integração estiver ativa.', verbose_name='URL do webhook')),
                ('status_conexao', models.CharField(choices=[('nao_testado', 'Ainda não verificada'), ('configurado', 'Configurada'), ('erro', 'Com erro')], default='nao_testado', max_length=20, verbose_name='Status da conexão')),
                ('ultima_verificacao_em', models.DateTimeField(blank=True, null=True, verbose_name='Última verificação')),
                ('mensagem_conexao', models.TextField(blank=True, verbose_name='Mensagem da conexão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_gateway_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Último administrador')),
            ],
            options={
                'verbose_name': 'Configuração de gateway',
                'verbose_name_plural': 'Configurações de gateway',
                'ordering': ['-atualizado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('chave', 1)), name='gateway_config_chave_unica'), models.CheckConstraint(condition=models.Q(('ativo', False), models.Q(('gateway', 'nenhum'), _negated=True), _connector='OR'), name='gateway_config_ativo_provedor'), models.CheckConstraint(condition=models.Q(('ativo', False), ('aceita_cartao', True), ('aceita_boleto', True), ('aceita_pix', True), _connector='OR'), name='gateway_config_metodo_ativo')],
            },
        ),
    ]
