# Generated by Django 5.2.9 on 2025-12-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Secção/Grupo')),
                ('icone_fa', models.CharField(default='fa-solid fa-link', max_length=30, verbose_name='Ícone FontAwesome')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Secção de Link',
                'verbose_name_plural': 'Secções de Links',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField(verbose_name='Endereço URL (http://...)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição (Opcional)')),
                ('is_download', models.BooleanField(default=False, verbose_name='É um Download (Mostrar botão)?')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.secaolink', verbose_name='Secção')),
            ],
            options={
                'verbose_name': 'Item de Link/Download',
                'verbose_name_plural': 'Itens de Links/Downloads',
                'ordering': ['titulo'],
            },
        ),
    ]
