# Generated by Django 5.2.9 on 2025-12-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Forma de Doação')),
                ('tipo', models.CharField(choices=[('PIX', 'Pix (Chave)'), ('CONTA', 'Depósito/Transferência'), ('OUTRO', 'Outro Método/Link')], default='PIX', max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Instruções ou Descrição')),
                ('chave_pix', models.CharField(blank=True, max_length=200, verbose_name='Chave PIX ou QR Code URL')),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('conta', models.CharField(blank=True, max_length=30, verbose_name='Conta / Favorecido')),
                ('ordem', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Forma de Doação',
                'verbose_name_plural': 'Formas de Doação',
                'ordering': ['ordem'],
            },
        ),
    ]
