# Generated by Django 5.2.9 on 2025-12-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formadoacao',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='pix_qrcodes/', verbose_name='QR Code (Imagem PNG/JPG)'),
        ),
        migrations.AlterField(
            model_name='formadoacao',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave PIX ou Código'),
        ),
    ]
