# Generated by Django 5.2.9 on 2026-06-03 23:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_formadoacao_qr_code_alter_formadoacao_chave_pix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaDoacaoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Apoie a Causa Espírita', max_length=200, verbose_name='Título Principal')),
                ('texto_apelo', ckeditor.fields.RichTextField(default='Sua doação é fundamental para mantermos nossas atividades.', verbose_name='Texto de Apelo')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='doacoes/capas/', verbose_name='Imagem de Destaque')),
                ('titulo_socio', models.CharField(default='Seja um Sócio Contribuinte', max_length=200, verbose_name='Título da Seção Sócio')),
                ('texto_socio', ckeditor.fields.RichTextField(blank=True, help_text='Explique a importância, valores sugeridos, etc.', null=True, verbose_name='Texto sobre ser Sócio')),
                ('link_socio', models.URLField(blank=True, null=True, verbose_name='Link Externo para Formulário de Sócio (Opcional)')),
            ],
            options={
                'verbose_name': 'Configuração da Página de Doações',
            },
        ),
    ]
