# Generated by Django 5.2.9 on 2025-12-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, verbose_name='Dia da Semana')),
                ('horario', models.CharField(max_length=50, verbose_name='Horário (ex: 15h às 17h)')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Atividade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Sub-atividades')),
            ],
            options={
                'verbose_name': 'Atividade Semanal',
                'verbose_name_plural': 'Atividades Semanais',
                'ordering': ['dia', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='Doutrinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('palestrante', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('imagem', models.ImageField(upload_to='doutrinarias/', verbose_name='Foto de Divulgação (Instagram)')),
                ('descricao', models.TextField(blank=True, verbose_name='Detalhes')),
            ],
            options={
                'verbose_name': 'Palestra Doutrinária',
                'verbose_name_plural': 'Doutrinárias (Agenda)',
                'ordering': ['data_hora'],
            },
        ),
    ]
