# Generated by Django 5.2.9 on 2025-12-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nome do Evento/Curso')),
                ('data_evento', models.DateTimeField(verbose_name='Data e Horário')),
                ('local', models.CharField(default='Sede da FEPI', max_length=200, verbose_name='Local')),
                ('imagem', models.ImageField(upload_to='cursos/', verbose_name='Cartaz de Divulgação')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('link_inscricao', models.URLField(blank=True, null=True, verbose_name='Link para Inscrição (Forms/Whats)')),
            ],
            options={
                'verbose_name': 'Curso ou Evento Especial',
                'verbose_name_plural': 'Cursos & Eventos',
                'ordering': ['data_evento'],
            },
        ),
    ]
