# Generated by Django 5.2.9 on 2025-12-12 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0002_cursoevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoevento',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição Detalhada'),
        ),
        migrations.AlterField(
            model_name='doutrinaria',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Detalhes'),
        ),
    ]
