# Generated by Django 5.2.9 on 2025-12-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0003_alter_cursoevento_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoevento',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Link Amigável'),
        ),
        migrations.AlterField(
            model_name='doutrinaria',
            name='imagem',
            field=models.ImageField(upload_to='doutrinarias/', verbose_name='Foto de Divulgação'),
        ),
    ]
