# Generated by Django 5.2.9 on 2025-12-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0004_cursoevento_slug_alter_doutrinaria_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadesemanal',
            options={'ordering': ['dia', 'horario'], 'verbose_name': 'Atividade Semanal', 'verbose_name_plural': 'Programação da Semana'},
        ),
        migrations.AlterModelOptions(
            name='doutrinaria',
            options={'ordering': ['data_hora'], 'verbose_name': 'Palestra Pública', 'verbose_name_plural': 'Palestras Públicas (Agenda)'},
        ),
    ]
